// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqhatprtkevixjnwakrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxaGF0cHJ0a2V2aXhqbndha3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjE5MjIsImV4cCI6MjA2MjY5NzkyMn0.tuk9jKqqcsLCsct2Nd2jZDJnvZ26LS57W-yCfmXzIPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);